title: Mahmed hameed
name: Mahmed hameed
description: IT & Cyber Security Portfolio
url: https://mahmed-hameed.github.io
baseurl: ""  # user site

remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-include-cache

permalink: /:categories/:title/

markdown: kramdown
kramdown:
  input: GFM

minimal_mistakes_skin: air  # try default, dark, contrast, etc.

author:
  name: "Mahmed hameed"
  avatar: /assets/site/avatar.jpg   # optional placeholder
  bio: "IT • Cyber Security"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/Mahmed-hameed"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/mahmed-hameed/"
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:Mahmed.h2025@gmail.com"

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      classes: wide

collections:
  projects:
    output: true
    permalink: /projects/:path/

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

sass:
  style: compressed
